### PR TITLE
Update experience to newer aframe

### PR DESCRIPTION
**Pull request by cabanier**
This fixes issues with headset other than Quest 2.
This also hides the AR button if the headset if capable of VR

### CODE REVIEW

**Comment by talkol** [comment]
Hi!

You're working for Meta, right?

1. My URL [spiderman.webvr.link](https://spiderman.webvr.link/) is still getting quite a lot of traffic (according to my Google Analytics which I'll be happy to share with you), what do you want to do with this URL? If I accept your PR, because you changed the CNAME, all the traffic to my custom domain will be broken.

2. There's a typo in the URL that you put - https://cityslingvr.arvr.social vs https://citysling.arvr.social

3. Your version crashes on my desktop Chrome browser, in case somebody visits the site from desktop by accident

4. I assume you removed all the Spider-Man branding due to copyright reasons? Is Meta linking to the game from anywhere?

**Comment by cabanier** [comment]
Yes, I work for meta. Thanks for reaching out!
We did indeed remove all the spiderman branding because we want to put this experience on our new tab page. Happy to keep your name in the startup page.

**Comment by cabanier** [comment]
If you want to continue hosting, that is fine as well. 
The page is not working on new headsets because you're using an old a-frame.

**Comment by talkol** [comment]
I had a little trouble keeping the dependencies up-to-date because I don't have a headset anyone. I'll be getting the Quest 3 so I can see if things work. Why did you close the PR?

**Comment by cabanier** [comment]
> I had a little trouble keeping the dependencies up-to-date because I don't have a headset anyone.

I see :-) Yes, without a headset that would be hard. Didn't you also do flappybird? That one also needs to be updated.

>  I'll be getting the Quest 3 so I can see if things work. Why did you close the PR?

I made so many changes and made it target my deployment so it's not compatible with your workflow. If you want to continue hosting it, I will remove that part.

**Comment by cabanier** [comment]
@talkol let me know what you prefer. I can patch up and host either experiences or happy to patch them up and have you host them.
If you want us to display them on the Quest browser landing page, please submit both experiences here: fb.me/ntp

**Comment by talkol** [comment]
I think that because I don't have a headset currently, it's best that you patch both and host both fixed versions. I assume that your versions will comply with Meta's requirements (like losing the Spider-Man branding). I'll be happy for you to add your versions to the Quest browser landing page. I'm not looking for any credit, just for people to enjoy them freely.

Thank you for your help!

When I get my Quest 3 in the future, I'll cherry pick your changes and update the version that I host at spiderman.webvr.link and this version will keep the Spider-Man branding :) I think it's fair use and it doesn't harm anyone. But I understand why you can't publish the Spider-Man version on the Quest landing page, it's safer for Meta to publish the generic one.

**Comment by cabanier** [comment]
Thanks! I will make sure to continue your name on the landing page.

I hope you enjoy your Quest 3. It's a great device :-)

**Pull request closed without merging**
